import { CropContract } from "@/types/contract";

export const mockContracts: CropContract[] = [
  {
    id: "pcm-001",
    tokenId: 1,
    cropName: "Heritage Red Fife Wheat",
    cropCategory: "grain",
    farmName: "Sunrise Ridge Farm",
    farmerName: "James Colton",
    region: "Flathead Valley",
    state: "Montana",
    country: "USA",
    harvestDate: "2026-07-15",
    deliveryDate: "2026-08-01",
    quantityKg: 500,
    pricePerKgUsdc: 1.85,
    totalValueUsdc: 925,
    status: "available",
    description:
      "Organically grown Red Fife wheat — a 19th-century Canadian landrace variety prized by artisan bakers for its complex, nutty flavour and superior gluten structure.",
    gradingStandard: "USDA Organic Certified",
    placeholderGradient: "from-amber-700 to-yellow-600",
    mintedAt: "2026-03-01",
    contractAddress: "0x1a2b3c4d5e6f",
    imageUrl: "/crops/red-fife-wheat.jpg",
  },
  {
    id: "pcm-002",
    tokenId: 2,
    cropName: "Purple Barley",
    cropCategory: "grain",
    farmName: "Cascade Harvest Co.",
    farmerName: "Miriam Osei",
    region: "Willamette Valley",
    state: "Oregon",
    country: "USA",
    harvestDate: "2026-08-10",
    deliveryDate: "2026-08-25",
    quantityKg: 300,
    pricePerKgUsdc: 2.4,
    totalValueUsdc: 720,
    status: "sold",
    description:
      "Vibrant purple hull-less barley grown without pesticides. High in anthocyanins and beta-glucan. Sought after by specialty breweries and health food distributors.",
    gradingStandard: "Oregon Tilth Certified Organic",
    placeholderGradient: "from-purple-800 to-violet-600",
    mintedAt: "2026-02-20",
    contractAddress: "0x2b3c4d5e6f7a",
    imageUrl: "/crops/purple-barley.jpg",
  },
  {
    id: "pcm-003",
    tokenId: 3,
    cropName: "Heirloom San Marzano Tomatoes",
    cropCategory: "vegetable",
    farmName: "Terra Bella Gardens",
    farmerName: "Sofia Ricci",
    region: "Central Valley",
    state: "California",
    country: "USA",
    harvestDate: "2026-09-05",
    deliveryDate: "2026-09-12",
    quantityKg: 200,
    pricePerKgUsdc: 4.2,
    totalValueUsdc: 840,
    status: "available",
    description:
      "Authentic San Marzano-style tomatoes grown from Italian heirloom seed stock. Low acidity, meaty flesh, and exceptional sauce quality. Pre-contracted for restaurant use.",
    gradingStandard: "California Certified Organic Farmers (CCOF)",
    placeholderGradient: "from-red-700 to-orange-500",
    mintedAt: "2026-03-05",
    imageUrl: "/crops/san-marzano-tomatoes.jpg",
  },
  {
    id: "pcm-004",
    tokenId: 4,
    cropName: "Emmer Farro",
    cropCategory: "grain",
    farmName: "Green Hollow Farm",
    farmerName: "Tobias Gruber",
    region: "Finger Lakes",
    state: "New York",
    country: "USA",
    harvestDate: "2026-07-28",
    deliveryDate: "2026-08-10",
    quantityKg: 400,
    pricePerKgUsdc: 3.1,
    totalValueUsdc: 1240,
    status: "redeemable",
    description:
      "Ancient emmer farro — one of the first domesticated crops. Rich, nutty flavour with a pleasantly chewy texture. Popular with fine dining restaurants and specialty grain distributors.",
    gradingStandard: "Certified Naturally Grown",
    placeholderGradient: "from-yellow-800 to-amber-500",
    mintedAt: "2026-01-15",
    imageUrl: "/crops/emmer-farro.jpg",
  },
  {
    id: "pcm-005",
    tokenId: 5,
    cropName: "Black Garlic",
    cropCategory: "specialty",
    farmName: "Moonfield Specialty Crops",
    farmerName: "Hyun-Ji Park",
    region: "Hudson Valley",
    state: "New York",
    country: "USA",
    harvestDate: "2026-06-20",
    deliveryDate: "2026-07-15",
    quantityKg: 80,
    pricePerKgUsdc: 22.0,
    totalValueUsdc: 1760,
    status: "available",
    description:
      "Hand-harvested black garlic, slow-fermented over 40 days. Balsamic-sweet umami depth. Highly prized by Michelin-starred chefs and high-end specialty food distributors.",
    gradingStandard: "GAP Certified",
    placeholderGradient: "from-gray-800 to-stone-600",
    mintedAt: "2026-03-08",
    imageUrl: "/crops/black-garlic.jpg",
  },
  {
    id: "pcm-006",
    tokenId: 6,
    cropName: "Artisan Blue Popcorn",
    cropCategory: "grain",
    farmName: "Prairie Sky Farm",
    farmerName: "Roy Whitefeather",
    region: "Loess Hills",
    state: "Iowa",
    country: "USA",
    harvestDate: "2026-10-01",
    deliveryDate: "2026-10-20",
    quantityKg: 350,
    pricePerKgUsdc: 2.8,
    totalValueUsdc: 980,
    status: "available",
    description:
      "Heirloom blue popcorn grown from Cherokee heritage seed. Vivid blue kernels, tender hull-less pop. Prized by specialty snack brands and farm-to-table restaurants.",
    gradingStandard: "Non-GMO Project Verified",
    placeholderGradient: "from-blue-800 to-indigo-600",
    mintedAt: "2026-03-10",
    imageUrl: "/crops/blue-popcorn.jpg",
  },
  {
    id: "pcm-007",
    tokenId: 7,
    cropName: "Persian Saffron",
    cropCategory: "herb",
    farmName: "High Desert Botanicals",
    farmerName: "Leila Nazari",
    region: "Sonoran Highlands",
    state: "Arizona",
    country: "USA",
    harvestDate: "2026-11-01",
    deliveryDate: "2026-11-20",
    quantityKg: 2,
    pricePerKgUsdc: 3200,
    totalValueUsdc: 6400,
    status: "redeemed",
    description:
      "Hand-harvested saffron threads from crocus sativus. ISO 3632 Grade 1. Laboratory tested for crocin, picrocrocin, and safranal levels. For specialty importers and luxury food brands.",
    gradingStandard: "ISO 3632 Grade 1",
    placeholderGradient: "from-orange-600 to-red-500",
    mintedAt: "2025-11-01",
    imageUrl: "/crops/persian-saffron.jpg",
  },
  {
    id: "pcm-008",
    tokenId: 8,
    cropName: "Spelt Berries",
    cropCategory: "grain",
    farmName: "Keystone Heritage Grains",
    farmerName: "Anna Ziegler",
    region: "Lancaster County",
    state: "Pennsylvania",
    country: "USA",
    harvestDate: "2026-08-05",
    deliveryDate: "2026-08-18",
    quantityKg: 600,
    pricePerKgUsdc: 1.65,
    totalValueUsdc: 990,
    status: "available",
    description:
      "Ancient European spelt — higher protein and fibre than modern wheat. Nuttier, more digestible. Ideal for artisan bakers, pasta makers, and specialty health food retailers.",
    gradingStandard: "Pennsylvania Certified Organic",
    placeholderGradient: "from-lime-700 to-green-600",
    mintedAt: "2026-03-12",
    imageUrl: "/crops/spelt-berries.jpg",
  },
];

export const cropCategories = [
  "All",
  "Grain",
  "Vegetable",
  "Herb",
  "Fruit",
  "Legume",
  "Specialty",
];

export const contractStatuses = [
  { value: "all", label: "All Status" },
  { value: "available", label: "Available" },
  { value: "sold", label: "Sold" },
  { value: "redeemable", label: "Ready to Redeem" },
  { value: "redeemed", label: "Completed" },
];
