import { CropContract } from "@/types/contract";

export const mockContracts: CropContract[] = [
  {
    id: "pcm-001",
    tokenId: 1,
    cropName: "Heritage Red Fife Wheat",
    cropCategory: "grain",
    farmName: "Sunrise Ridge Farm",
    farmerName: "James Colton",
    region: "Flathead Valley",
    state: "Montana",
    country: "USA",
    harvestDate: "2026-07-15",
    deliveryDate: "2026-08-01",
    deliveryMethod: "Buyer Provided",
    deliveryLocation: "Pick-up at Seller's Location",
    quantityUnits: 500,
    unitType: "kg",
    pricePerUnitUsdc: 1.85,
    totalValueUsdc: 925,
    gradingStandard: "USDA Organic Certified",
    qualityStandards: {
      moisture: "<14%",
      totalDefects: "<2%",
      specialMetrics: "Organically grown, no pesticides",
    },
    status: "available",
    description:
      "Organically grown Red Fife wheat — a 19th-century Canadian landrace variety prized by artisan bakers for its complex, nutty flavour and superior gluten structure.",
    placeholderGradient: "from-amber-700 to-yellow-600",
    mintedAt: "2026-03-01",
    contractAddress: "0x1a2b3c4d5e6f",
    imageUrl: "/crops/red-fife-wheat.jpg",
  },
  {
    id: "pcm-002",
    tokenId: 2,
    cropName: "Purple Barley",
    cropCategory: "grain",
    farmName: "Cascade Harvest Co.",
    farmerName: "Miriam Osei",
    region: "Willamette Valley",
    state: "Oregon",
    country: "USA",
    harvestDate: "2026-08-10",
    deliveryDate: "2026-08-25",
    deliveryMethod: "Buyer Provided",
    deliveryLocation: "Pick-up at Seller's Location",
    quantityUnits: 300,
    unitType: "kg",
    pricePerUnitUsdc: 2.4,
    totalValueUsdc: 720,
    gradingStandard: "Oregon Tilth Certified Organic",
    qualityStandards: {
      moisture: "<14%",
      totalDefects: "<2%",
      specialMetrics: "Grown without pesticides, high in anthocyanins",
    },
    status: "sold",
    description:
      "Vibrant purple hull-less barley grown without pesticides. High in anthocyanins and beta-glucan. Sought after by specialty breweries and health food distributors.",
    placeholderGradient: "from-purple-800 to-violet-600",
    mintedAt: "2026-02-20",
    contractAddress: "0x2b3c4d5e6f7a",
    imageUrl: "/crops/purple-barley.jpg",
  },
  {
    id: "pcm-003",
    tokenId: 3,
    cropName: "Heirloom San Marzano Tomatoes",
    cropCategory: "vegetable",
    farmName: "Terra Bella Gardens",
    farmerName: "Sofia Ricci",
    region: "Central Valley",
    state: "California",
    country: "USA",
    harvestDate: "2026-09-05",
    deliveryDate: "2026-09-12",
    deliveryMethod: "Seller Delivered",
    deliveryLocation: "Buyer's Warehouse",
    quantityUnits: 200,
    unitType: "kg",
    pricePerUnitUsdc: 4.2,
    totalValueUsdc: 840,
    gradingStandard: "California Certified Organic Farmers (CCOF)",
    qualityStandards: {
      moisture: "<90%",
      totalDefects: "<3%",
      specialMetrics: "Italian heirloom seed stock, low acidity",
    },
    status: "available",
    description:
      "Authentic San Marzano-style tomatoes grown from Italian heirloom seed stock. Low acidity, meaty flesh, and exceptional sauce quality. Pre-contracted for restaurant use.",
    placeholderGradient: "from-red-700 to-orange-500",
    mintedAt: "2026-03-05",
    imageUrl: "/crops/san-marzano-tomatoes.jpg",
  },
  {
    id: "pcm-004",
    tokenId: 4,
    cropName: "Emmer Farro",
    cropCategory: "grain",
    farmName: "Green Hollow Farm",
    farmerName: "Tobias Gruber",
    region: "Finger Lakes",
    state: "New York",
    country: "USA",
    harvestDate: "2026-07-28",
    deliveryDate: "2026-08-10",
    deliveryMethod: "Buyer Provided",
    deliveryLocation: "Pick-up at Seller's Location",
    quantityUnits: 400,
    unitType: "kg",
    pricePerUnitUsdc: 3.1,
    totalValueUsdc: 1240,
    gradingStandard: "Certified Naturally Grown",
    qualityStandards: {
      moisture: "<14%",
      totalDefects: "<2%",
      foreignMaterial: "<0.5%",
    },
    status: "redeemable",
    description:
      "Ancient emmer farro — one of the first domesticated crops. Rich, nutty flavour with a pleasantly chewy texture. Popular with fine dining restaurants and specialty grain distributors.",
    placeholderGradient: "from-yellow-800 to-amber-500",
    mintedAt: "2026-01-15",
    imageUrl: "/crops/emmer-farro.jpg",
  },
  {
    id: "pcm-005",
    tokenId: 5,
    cropName: "Black Garlic",
    cropCategory: "specialty",
    farmName: "Moonfield Specialty Crops",
    farmerName: "Hyun-Ji Park",
    region: "Hudson Valley",
    state: "New York",
    country: "USA",
    harvestDate: "2026-06-20",
    deliveryDate: "2026-07-15",
    deliveryMethod: "Seller Delivered",
    deliveryLocation: "Buyer's Warehouse",
    quantityUnits: 80,
    unitType: "kg",
    pricePerUnitUsdc: 22.0,
    totalValueUsdc: 1760,
    gradingStandard: "GAP Certified",
    qualityStandards: {
      specialMetrics: "Hand-harvested, slow-fermented over 40 days",
    },
    status: "available",
    description:
      "Hand-harvested black garlic, slow-fermented over 40 days. Balsamic-sweet umami depth. Highly prized by Michelin-starred chefs and high-end specialty food distributors.",
    placeholderGradient: "from-gray-800 to-stone-600",
    mintedAt: "2026-03-08",
    imageUrl: "/crops/black-garlic.jpg",
  },
  {
    id: "pcm-006",
    tokenId: 6,
    cropName: "Artisan Blue Popcorn",
    cropCategory: "grain",
    farmName: "Prairie Sky Farm",
    farmerName: "Roy Whitefeather",
    region: "Loess Hills",
    state: "Iowa",
    country: "USA",
    harvestDate: "2026-10-01",
    deliveryDate: "2026-10-20",
    deliveryMethod: "Buyer Provided",
    deliveryLocation: "Pick-up at Seller's Location",
    quantityUnits: 350,
    unitType: "kg",
    pricePerUnitUsdc: 2.8,
    totalValueUsdc: 980,
    gradingStandard: "Non-GMO Project Verified",
    qualityStandards: {
      moisture: "<14%",
      totalDefects: "<2%",
      specialMetrics: "Cherokee heritage seed, hull-less",
    },
    status: "available",
    description:
      "Heirloom blue popcorn grown from Cherokee heritage seed. Vivid blue kernels, tender hull-less pop. Prized by specialty snack brands and farm-to-table restaurants.",
    placeholderGradient: "from-blue-800 to-indigo-600",
    mintedAt: "2026-03-10",
    imageUrl: "/crops/blue-popcorn.jpg",
  },
  {
    id: "pcm-007",
    tokenId: 7,
    cropName: "Persian Saffron",
    cropCategory: "herb",
    farmName: "High Desert Botanicals",
    farmerName: "Leila Nazari",
    region: "Sonoran Highlands",
    state: "Arizona",
    country: "USA",
    harvestDate: "2026-11-01",
    deliveryDate: "2026-11-20",
    deliveryMethod: "Seller Delivered",
    deliveryLocation: "Buyer's Warehouse",
    quantityUnits: 2,
    unitType: "kg",
    pricePerUnitUsdc: 3200,
    totalValueUsdc: 6400,
    gradingStandard: "ISO 3632 Grade 1",
    qualityStandards: {
      specialMetrics: "Laboratory tested for crocin, picrocrocin, and safranal levels",
    },
    status: "redeemed",
    description:
      "Hand-harvested saffron threads from crocus sativus. ISO 3632 Grade 1. Laboratory tested for crocin, picrocrocin, and safranal levels. For specialty importers and luxury food brands.",
    placeholderGradient: "from-orange-600 to-red-500",
    mintedAt: "2025-11-01",
    imageUrl: "/crops/persian-saffron.jpg",
  },
  {
    id: "pcm-008",
    tokenId: 8,
    cropName: "Spelt Berries",
    cropCategory: "grain",
    farmName: "Keystone Heritage Grains",
    farmerName: "Anna Ziegler",
    region: "Lancaster County",
    state: "Pennsylvania",
    country: "USA",
    harvestDate: "2026-08-05",
    deliveryDate: "2026-08-18",
    deliveryMethod: "Buyer Provided",
    deliveryLocation: "Pick-up at Seller's Location",
    quantityUnits: 600,
    unitType: "kg",
    pricePerUnitUsdc: 1.65,
    totalValueUsdc: 990,
    gradingStandard: "Pennsylvania Certified Organic",
    qualityStandards: {
      moisture: "<14%",
      totalDefects: "<2%",
      foreignMaterial: "<0.5%",
      specialMetrics: "Ancient European variety, higher protein than modern wheat",
    },
    status: "available",
    description:
      "Ancient European spelt — higher protein and fibre than modern wheat. Nuttier, more digestible. Ideal for artisan bakers, pasta makers, and specialty health food retailers.",
    placeholderGradient: "from-lime-700 to-green-600",
    mintedAt: "2026-03-12",
    imageUrl: "/crops/spelt-berries.jpg",
  },
  // ── Real contracts from Marias River Farms ──────────────────────────────────
  {
    id: "pcm-009",
    tokenId: 9,
    cropName: "Grain Chickpeas US No. 1",
    cropCategory: "legume",
    farmName: "Marias River Farms",
    farmerName: "Stephen Skierka",
    farmerEmail: "contact@mariasriverfarms.com",
    farmerPhone: "+1 406-680-7333",
    region: "Chester",
    state: "Montana",
    country: "USA",
    deliveryDate: "2026-09-01",
    deliveryMethod: "Buyer Provided",
    deliveryLocation: "Pick-up at Seller's Location",
    quantityUnits: 10,
    unitType: "Tote Bag",
    unitSizeLbs: 2000,
    pricePerUnitUsdc: 100,
    totalValueUsdc: 1000,
    gradingStandard: "US No. 1",
    qualityStandards: {
      moisture: "<14%",
      totalDefects: "<2%",
      totalDamaged: "<2%",
      foreignMaterial: "<0.5%",
      contrasting: "<1%",
      testWeight: ">55 lbs.",
      specialMetrics:
        "Crop grown with intercropping, no pesticides, and soil conservation practices. Special separating and cleaning process.",
    },
    dockage: "Allowed by percentage above any quality standard",
    status: "available",
    description:
      "Chickpeas grown to US No. 1 grade standards using intercropping, zero pesticides, and soil conservation practices on the Hi-Line plains of northern Montana. Special separating and cleaning process ensures exceptional purity.",
    placeholderGradient: "from-yellow-600 to-amber-400",
    mintedAt: "2026-03-20",
  },
  {
    id: "pcm-010",
    tokenId: 10,
    cropName: "Grain Flax US No. 1",
    cropCategory: "grain",
    farmName: "Marias River Farms",
    farmerName: "Stephen Skierka",
    farmerEmail: "contact@mariasriverfarms.com",
    farmerPhone: "+1 406-680-7333",
    region: "Chester",
    state: "Montana",
    country: "USA",
    deliveryDate: "2026-09-01",
    deliveryMethod: "Buyer Provided",
    deliveryLocation: "Pick-up at Seller's Location",
    quantityUnits: 10,
    unitType: "Tote Bag",
    unitSizeLbs: 2000,
    pricePerUnitUsdc: 800,
    totalValueUsdc: 8000,
    gradingStandard: "US No. 1",
    qualityStandards: {
      moisture: "<14%",
      totalDefects: "<2%",
      totalDamaged: "<10%",
      foreignMaterial: "<0.5%",
      contrasting: "<1%",
      testWeight: ">49 lbs.",
      specialMetrics:
        "Crop grown with intercropping, no pesticides, and soil conservation practices. Special separating and cleaning process.",
    },
    dockage: "Allowed by percentage above any quality standard",
    status: "available",
    description:
      "Premium flax grown to US No. 1 grade on the high plains of northern Montana. Cultivated with intercropping and zero pesticides. Sought after by natural food processors and health product manufacturers.",
    placeholderGradient: "from-blue-600 to-cyan-400",
    mintedAt: "2026-03-20",
  },
  {
    id: "pcm-011",
    tokenId: 11,
    cropName: "Grain Hulless Oats US No. 1",
    cropCategory: "grain",
    farmName: "Marias River Farms",
    farmerName: "Stephen Skierka",
    farmerEmail: "contact@mariasriverfarms.com",
    farmerPhone: "+1 406-680-7333",
    region: "Chester",
    state: "Montana",
    country: "USA",
    deliveryDate: "2026-09-01",
    deliveryMethod: "Buyer Provided",
    deliveryLocation: "Pick-up at Seller's Location",
    quantityUnits: 10,
    unitType: "Tote Bag",
    unitSizeLbs: 2000,
    pricePerUnitUsdc: 240,
    totalValueUsdc: 2400,
    gradingStandard: "US No. 1",
    qualityStandards: {
      moisture: "<14%",
      totalDefects: "<3%",
      totalDamaged: "<3%",
      foreignMaterial: "<0.5%",
      contrasting: "<1%",
      testWeight: ">36 lbs.",
      specialMetrics:
        "Crop grown with intercropping, no pesticides, and soil conservation practices. Special separating and cleaning process.",
    },
    dockage: "Allowed by percentage above any quality standard",
    status: "available",
    description:
      "Hull-less oats grown to US No. 1 grade standards in Chester, Montana. Intercropped with no pesticides for superior grain quality. Ready-to-process with no hulling required — ideal for oat processors and specialty food producers.",
    placeholderGradient: "from-green-600 to-teal-400",
    mintedAt: "2026-03-20",
  },
];

export const cropCategories = [
  "All",
  "Grain",
  "Vegetable",
  "Herb",
  "Fruit",
  "Legume",
  "Specialty",
];

export const contractStatuses = [
  { value: "all", label: "All Status" },
  { value: "available", label: "Available" },
  { value: "sold", label: "Sold" },
  { value: "redeemable", label: "Ready to Redeem" },
  { value: "redeemed", label: "Completed" },
];
